# Generated by Django 3.2.3 on 2021-06-09 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия автора')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('summary', models.TextField(blank=True, verbose_name='Сведения об авторе')),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='photos_author/%Y/%m/%d', verbose_name='Фото автора')),
            ],
        ),
        migrations.CreateModel(
            name='RubricPublications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=90, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Рубрику',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TypesOfSports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Вид спорта')),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('annotations', models.TextField(verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Текст статьи')),
                ('photo', models.ImageField(upload_to='photos_publications/%Y/%m/%d', verbose_name='Фотография')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publications.author', verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publications.rubricpublications', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Материалы публикаций',
                'verbose_name_plural': 'Материалы публикаций',
                'ordering': ['time_create', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя спортсмена')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия спортсмена')),
                ('summary', models.TextField(blank=True, verbose_name='Информация о спортсмене')),
                ('awards', models.TextField(blank=True, verbose_name='Список наград спортсмена')),
                ('photo', models.ImageField(upload_to='photos_athlete/%Y/%m/%d', verbose_name='Фото спортсмена')),
                ('type_sports', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publications.typesofsports')),
            ],
        ),
    ]
